/**
 * One-off migration: renames existing AYICRIP-2026-CC-NNNN summit IDs to
 * AYS-2026-CC-NNNN, matching the current ID format generated by
 * server/utils/ids.js. Safe to re-run — it only touches documents whose
 * summitId still starts with "AYICRIP-".
 *
 * Usage: node backend/scripts/migrateSummitIds.js
 */
const path = require("path");
require("dotenv").config({ path: path.join(__dirname, "..", ".env") });
const mongoose = require("mongoose");
const User = require("../server/models/User");

const MONGO_URI = process.env.MONGO_URI;

async function migrate() {
  if (!MONGO_URI) {
    console.error("MONGO_URI not found (expected in backend/.env).");
    process.exit(1);
  }

  await mongoose.connect(MONGO_URI);
  console.log("Connected to MongoDB.");

  const outdated = await User.find({ summitId: { $regex: "^AYICRIP-" } });
  console.log(`Found ${outdated.length} delegate(s) with an AYICRIP- summit ID.`);

  for (const user of outdated) {
    const oldId = user.summitId;
    const newId = oldId.replace(/^AYICRIP-/, "AYS-");
    user.summitId = newId;
    await user.save();
    console.log(`${oldId} -> ${newId} (${user.fullName})`);
  }

  console.log(`Done. ${outdated.length} summit ID(s) updated.`);
  await mongoose.disconnect();
  process.exit(0);
}

migrate().catch((error) => {
  console.error("Migration failed:", error);
  process.exit(1);
});
